---
- name: Install Apache on Ubuntu and RHEL
  hosts: servers
  become: yes

  tasks:
    - name: Install Apache on Ubuntu
      apt:
        name: apache2
        state: present
        update_cache: yes
      when: ansible_distribution == "Ubuntu"

    - name: Start and enable Apache on Ubuntu
      service:
        name: apache2
        state: started
        enabled: yes
      when: ansible_distribution == "Ubuntu"

    - name: Install Apache on RHEL/CentOS
      yum:
        name: httpd
        state: present
      when: ansible_distribution == "RedHat"

    - name: Start and enable Apache on RHEL/CentOS
      service:
        name: httpd
        state: started
        enabled: yes
      when: ansible_distribution == "RedHat"
